### ISSUE TITLE
bug: empty calling connects to the same client

### ISSUE THREAD

**Issue by bharat-1809** [theiconik/piper-chat#1]
**Description**
When no client token is filled and the call button is pressed, the user is connected to himself. 

**Expectation**
Ideally, the call shouldn't be made when the ID to call is empty.

**Comment by theiconik** [comment]
Well, I have fixed that issue, but thank you for pointing it out and now I just realized it's not functioning properly. The client side is not receiving the emitted signal, don't know why. I'll have to check that out. Taking it down.
